# Change these first
owner: XCPCIO # Your GitHub username
repo: codeforces.uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Codeforces
    url: https://codeforces.com
  - name: Polygon
    url: https://polygon.codeforces.com
  - name: m1
    url: https://m1.codeforces.com
  - name: m2
    url: https://m2.codeforces.com
  - name: m3
    url: https://m3.codeforces.com
  - name: sta
    url: https://sta.codeforces.com
  - name: codeforc.es
    url: https://codeforc.es
  - name: ml
    url: https://codeforces.ml
  - name: cc
    url: https://codeforces.cc

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: codeforces.uptime.xcpcio.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://sta.codeforces.com/s/43864/favicon-96x96.png
  name: Codeforces uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
